"""Markdown report and figures for the Phase 5 leakage checks. Every number is read from the results."""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd


def _pm(x) -> str:
    return f"{x[0]:.4f} ± {x[1]:.4f}"


def _md_table(df: pd.DataFrame, fmt: dict[str, str] | None = None) -> str:
    fmt = fmt or {}
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            cells.append(fmt[c].format(v) if c in fmt and pd.notna(v) else str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _figures(res, c3, c3b, out: Path, fig_dir: Path) -> dict[str, str]:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig_dir.mkdir(parents=True, exist_ok=True)
    paths = {}

    fig, ax = plt.subplots(figsize=(8, 0.32 * len(c3) + 1.5))
    d = c3.iloc[::-1]
    ax.barh(d["feature"], d["macro_f1"], xerr=d["std"], color=["#c0504d" if k == "diagnostic" else "#4f81bd" for k in d["kind"]])
    ax.axvline(1 / 6 if res["label_mode"] == "6class" else 1 / 11, color="gray", ls=":", label="chance")
    ax.set_xlabel("macro-F1 on val, single feature (mean ± std over seeds)")
    ax.set_title("C3: one raw column at a time (red = diagnostic)")
    ax.legend()
    fig.tight_layout()
    paths["c3"] = "c3_single_feature.png"
    fig.savefig(fig_dir / paths["c3"], dpi=110)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 0.32 * len(c3b) + 1.5))
    d = c3b.iloc[::-1]
    ax.barh(d["removed"], d["delta_vs_full"], xerr=d["std"], color="#9bbb59")
    ax.axvline(0, color="k", lw=0.8)
    ax.set_xlabel("change in val macro-F1 when the column is removed")
    ax.set_title("C3b: leave one raw column out of the full model")
    fig.tight_layout()
    paths["c3b"] = "c3b_leave_one_out.png"
    fig.savefig(fig_dir / paths["c3b"], dpi=110)
    plt.close(fig)

    c4 = res["c4"]
    fig, ax = plt.subplots(figsize=(6, 4))
    names = ["random", "stream", "group", "val"]
    ax.bar(names, [c4[n][0] for n in names], yerr=[c4[n][1] for n in names], color=["#c0504d", "#f79646", "#4f81bd", "#9bbb59"])
    ax.set_ylabel("macro-F1")
    ax.set_title("C4: how the train pool is cut")
    fig.tight_layout()
    paths["c4"] = "c4_split_gap.png"
    fig.savefig(fig_dir / paths["c4"], dpi=110)
    plt.close(fig)
    return paths


def write_report(cfg, res, c1, c3, c3b, c5, schema, out: Path) -> Path:
    th = cfg["thresholds"]
    fig_dir = Path(cfg.get("leakage", {}).get("figures_dir", "./results/figures"))
    figs = _figures(res, c3, c3b, out, fig_dir)
    classes = {v: k for k, v in schema["label_map"].items()}
    ref, c2, c4 = res["reference"], res["c2"], res["c4"]
    L = [f"# Phase 5 - Leakage report ({res['label_mode']})", "",
         f"Auto-generated by `ppfeddata check`. RF {res['n_trees']} trees, seeds {res['seeds']}, macro-F1 on **val** "
         f"(groups never seen in training), D = {res['D']}, config_hash `{res['config_hash']}`. "
         "All thresholds are heuristics from `thresholds` in the config (spec mark: needs verification); "
         "this report only measures and flags, the decision is made at G2.", ""]

    refb = res["reference_balanced"]
    L += ["## Reference: full model", "",
          f"- unweighted RF, macro-F1 on val: **{_pm(ref['macro_f1'])}**; per-class F1: "
          + ", ".join(f"{classes[i]} {v:.3f}" for i, v in enumerate(ref["per_class_f1"])),
          f"- class-balanced RF, macro-F1 on val: **{_pm(refb['macro_f1'])}**; per-class F1: "
          + ", ".join(f"{classes[i]} {v:.3f}" for i, v in enumerate(refb["per_class_f1"])),
          "- val is class-balanced while the train pool is not, so the unweighted number is pulled down by the majority class.", ""]

    ab = res["ablations"]
    names = [classes[i] for i in range(len(ab["full"]["per_class_f1"]))]
    L += ["## Ablations for the G2 feature decision", "",
          "Class-balanced RF, macro-F1 on val (mean ± std over seeds) and per-class F1.", "",
          "| model | macro-F1 | " + " | ".join(names) + " |", "|---|---|" + "---|" * len(names)]
    for label, key in (("full core feature set", "full"),
                       ("+ diagnostic columns", "plus_diagnostic"),
                       (f"without time columns ({', '.join(ab['time_columns'])})", "without_time_columns")):
        if key not in ab:
            continue
        e = ab[key]
        L.append(f"| {label} | {_pm(e['macro_f1'])} | " + " | ".join(f"{v:.3f}" for v in e["per_class_f1"]) + " |")
    L.append("")
    if "plus_diagnostic" in ab:
        d = [b - a for a, b in zip(ab["full"]["per_class_f1"], ab["plus_diagnostic"]["per_class_f1"])]
        L += ["- change in per-class F1 when the diagnostic columns are added: " + ", ".join(f"{n} {v:+.3f}" for n, v in zip(names, d)), ""]
    else:
        L += ["- no diagnostic columns in this configuration.", ""]

    L += ["## C1 - presence matrix (from Phase 2)", "",
          "Columns empty (<= absent_presence_max) in some sub-classes and populated (>= present_presence_min) in others:", ""]
    mixed = c1[c1["mixed"]][["column", "n_empty_classes", "n_populated_classes", "max_presence", "populated_in"]]
    L += [_md_table(mixed, {"max_presence": "{:.3f}"}), ""]

    L += ["## C2 - RF on the `_is_na` flags only", ""]
    if c2.get("n_flags"):
        L += [f"- {c2['n_flags']} flags, macro-F1 on val **{_pm((c2['macro_f1'], c2['std']))}** vs chance {c2['chance']:.3f} "
              f"(flag threshold {th['na_only_f1_flag']}): {'**FLAGGED**' if c2['flag'] else 'not flagged'}",
              "- per-class F1: " + ", ".join(f"{classes[i]} {v:.3f}" for i, v in enumerate(c2["per_class_f1"])),
              "- flags by importance: " + ", ".join(f"{k} {v:.3f}" for k, v in list(c2["importance"].items())[:8]), ""]
    else:
        L += ["- no flags in the schema", ""]

    L += ["## C3 - each raw column alone", "",
          f"Class-balanced RF on one column. Flag threshold: macro-F1 or best per-class F1 > {th['single_feature_f1_flag']}. "
          f"Flagged: {', '.join(c3[c3['flag']]['feature']) or 'none'}.", "",
          _md_table(c3[["feature", "kind", "macro_f1", "std", "best_class", "best_class_f1", "flag"]], {"macro_f1": "{:.4f}", "std": "{:.4f}", "best_class_f1": "{:.4f}"}), "",
          f"Figure: `{fig_dir / figs['c3']}`", "",
          "### C3b - leave one column out of the full model", "",
          _md_table(c3b, {"macro_f1": "{:.4f}", "std": "{:.4f}", "delta_vs_full": "{:+.4f}"}), "",
          f"Figure: `{fig_dir / figs['c3b']}`", ""]

    L += ["## C4 - cutting the train pool by row, stream or group", "",
          f"{c4['folds']}-fold CV on the train pool (macro-F1, mean ± std over seeds); `val` = fit on the whole pool, test on val.", "",
          "| split | macro-F1 |", "|---|---|"]
    L += [f"| {n} | {_pm(c4[n])} |" for n in ("random", "stream", "group", "val")]
    L += ["", f"- gap random - group = **{c4['gap_random_minus_group']:+.4f}**, random - stream = **{c4['gap_random_minus_stream']:+.4f}** "
              f"(flag threshold {th['leakage_gap_flag']}): {'**FLAGGED**' if c4['flag'] else 'not flagged'}",
          f"- random - val = {c4['gap_random_minus_val']:+.4f} (informational: CV folds keep the imbalanced class mix, val is balanced, "
          "so the two macro-F1 values are not directly comparable)",
          f"Figure: `{fig_dir / figs['c4']}`", ""]

    L += ["## C5 - DoS vs DDoS inside one scenario (11-class data)", ""]
    if c5 is not None:
        L += [f"Flag: macro-F1 < {th['dos_ddos_f1_flag']} (binary chance = 0.5).", "",
              _md_table(c5, {"macro_f1": "{:.4f}", "std": "{:.4f}", "balanced_acc": "{:.4f}"}), ""]
        bad = c5[c5["flag_indistinguishable"]]["scenario"].tolist()
        L += [f"- scenarios flagged as not separable: {bad or 'none'}", ""]
    else:
        L += ["- 11-class processed data not found; run `preprocess --label-mode 11class` first.", ""]

    flagged = []
    if c2.get("flag"):
        flagged.append("C2")
    if c3["flag"].any():
        flagged.append("C3: " + ", ".join(c3[c3["flag"]]["feature"]))
    if c4["flag"]:
        flagged.append("C4")
    if c5 is not None and c5["flag_indistinguishable"].any():
        flagged.append("C5: " + ", ".join(c5[c5["flag_indistinguishable"]]["scenario"]))
    L += ["## Flags raised", "", *(f"- {x}" for x in flagged), "" if flagged else "- none", ""]

    path = out / "leakage_report.md"
    path.write_text("\n".join(L), encoding="utf-8")
    rep_dir = Path(cfg.get("leakage", {}).get("report_path", "./results/reports/leakage_report.md"))
    rep_dir.parent.mkdir(parents=True, exist_ok=True)
    rep_dir.write_text("\n".join(L), encoding="utf-8")
    return rep_dir
