"""Phase 13: the generated blocks of README.md.

The README keeps what does not change by hand (install, commands, layout) and takes everything that depends on a result from `results/interpretation.json`, the run ledger and
the trial session: the answers R1-R6 with their numbers, the reasons for using a CVAE although R1 and R2 are negative, the reference run times and the list of limitations.
`ppfeddata aggregate` rewrites the text between `<!-- BEGIN GENERATED: name -->` and `<!-- END GENERATED: name -->`, so the README cannot drift from the report.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pandas as pd

from ppfeddata import limitations as lim
from ppfeddata.interpret import PRIMARY

README = Path(__file__).resolve().parents[2] / "README.md"
README_VI = Path(__file__).resolve().parents[2] / "README.vi.md"
READMES = (README, README_VI)                                          # the same generated blocks (English, one set of sentence templates) in both languages
BLOCKS = ("results", "libraries", "times", "limitations")


def markers(name: str) -> tuple[str, str]:
    return f"<!-- BEGIN GENERATED: {name} -->", f"<!-- END GENERATED: {name} -->"


def _fmt(x: Any, nd: int = 3, dash: str = "-") -> str:
    return dash if x is None or (isinstance(x, float) and pd.isna(x)) else (f"{x:.{nd}f}" if isinstance(x, (int, float)) else str(x))


def results_block(R: dict[str, Any], cfg: dict[str, Any]) -> str:
    """The answers R1-R6, the reasons for the CVAE and the red flags (section 9.0 of the report) and the R6 candidate table, from interpretation.json."""
    from ppfeddata.interpret_report import answers

    m = R["meta"]
    L = [f"*Generated by `ppfeddata aggregate` from `results/interpretation.json` ({m['n_runs']} runs, seeds {m['seeds']}, {m['n_test_rows']:,} real test rows from {m['n_groups']} capture groups; "
         "macro-F1 on the real test split). The text is the one of section 9.0 of `results/reports/final_report.md`, which has the intervals, the red flags and the method (section 9.9 explains "
         "why the study uses a CVAE).*", ""]
    L += [f"- {a}" for a in answers(R, cfg)]
    W = R.get("why") or {}
    rows = R.get("R6", {}).get("candidates") or []
    if rows:
        L += ["", f"Candidate configurations of the recommendation rule (R6); macro-F1 of the {PRIMARY.upper()} classifier, mean over seeds:", "",
              "| configuration | TAug macro-F1 | TSTR macro-F1 | MIA AUC | epsilon (max) | time per round vs B3 | eligible |", "|---|---|---|---|---|---|---|"]
        for c in rows:
            L.append(f"| {c['label']} | {_fmt(c['taug_f1'], 4)} | {_fmt(c['tstr_f1'], 4)} | {_fmt(c['mia_auc'], 3)} | {_fmt(c['eps_max'], 3)} | {_fmt(c['time_ratio'], 2)} | {'yes' if c['eligible'] else 'no'} |")
    ref = {r["id"]: r for r in W.get("rows", [])}
    parts = [f"{lab} {name}: " + ", ".join(f"{clf.upper()} {v:.3f}" for clf, v in ref[k]["macro_f1"].items()) for k, lab, name in
             (("B0:TRTR", "B0", "real data only"), ("B1a:TRTR", "B1a", "class weights"), ("B1b:TRTR", "B1b", "SMOTE")) if k in ref]
    if parts:
        L += ["", "For reference (trained and tested on real data): " + "; ".join(parts) + "."]
    return "\n".join(L)


def hardware(cfg: dict[str, Any]) -> str | None:
    """The machine of the benchmark, as written in compute_budget.md."""
    p = Path(cfg["compute"]["runs_csv"]).parent / "reports" / "compute_budget.md"
    if not p.exists():
        return None
    m = re.search(r"Hardware/software: (.*?)\.\s+Commit", p.read_text(encoding="utf-8"), flags=re.S)
    return " ".join(m.group(1).split()) if m else None


def trial_session(cfg: dict[str, Any]) -> dict[str, Any] | None:
    from ppfeddata.run_experiment import status_path, workspace_cfg

    p = status_path(workspace_cfg(cfg, "trial"))
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def times_block(cfg: dict[str, Any]) -> str:
    """Wall time of the one-seed trial of the whole matrix (Gate G4), per configuration, from its session file."""
    s = trial_session(cfg)
    if not s or not s.get("items"):
        return "No trial session found (`artifacts/_trial`); see `results/reports/compute_budget.md` for the measured cost of one epoch and the extrapolation."
    items = [i for i in s["items"] if i.get("seconds") is not None and i.get("group") == "matrix"]
    total = sum(i["seconds"] for i in items) / 60
    hw = hardware(cfg)
    L = [f"Wall time of the whole matrix for **one seed**, run from scratch with one command (`python -m ppfeddata.cli run --stage trial`, seed {s['seeds']}), "
         f"{'on ' + hw if hw else 'on the machine of the experiments'}: **{total:.1f} min**. The evaluation of every generator (fidelity, privacy, TSTR and TAug with RF and MLP) is included. "
         "Source: `results/reports/g4_trial.md`; a Colab CPU session will differ.", "", "| configuration | status | minutes |", "|---|---|---|"]
    L += [f"| {i['id']} | {i['status']} | {i['seconds'] / 60:.1f} |" for i in items]
    return "\n".join(L)


def libraries_block() -> str:
    """Versions of the libraries the study depends on, as installed when the block is written (the exact lock is requirements-lock.txt)."""
    import platform

    from ppfeddata.package import lib_versions

    rows = [f"| {k} | {v} |" for k, v in lib_versions().items() if v]
    head = (f"Python {platform.python_version()} on {platform.system()} {platform.release()}. Versions installed when `ppfeddata aggregate` last wrote this block; "
            "the exact lock is `requirements-lock.txt` (a copy is in `results/repro/pip_freeze.txt`).")
    return "\n".join([head, "", "| library | version |", "|---|---|"] + rows)


def limitations_block(items: list[dict[str, str]]) -> str:
    return "\n".join([f"<details><summary>{len(items)} limitations (the list of section 10 of the final report and of page 5 of the demo)</summary>", ""]
                     + lim.render_md(items) + ["", "</details>"])


def replace_block(text: str, name: str, body: str) -> str:
    b, e = markers(name)
    i, j = text.find(b), text.find(e)
    if i < 0 or j < i:
        raise ValueError(f"README has no `{b}` ... `{e}` pair")
    return text[:i + len(b)] + "\n" + body.strip("\n") + "\n" + text[j:]


def update_readme(path: str | Path, cfg: dict[str, Any], R: dict[str, Any] | None, summ: pd.DataFrame | None = None) -> list[str]:
    """Rewrite the generated blocks of the README; returns the names written. A block whose source is missing is left as it is."""
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    done = []
    bodies = {"results": results_block(R, cfg) if R else None, "libraries": libraries_block(), "times": times_block(cfg), "limitations": limitations_block(lim.limitations(cfg, R, summ))}
    for name in BLOCKS:
        if bodies[name] is not None:
            text = replace_block(text, name, bodies[name])
            done.append(name)
    p.write_text(text, encoding="utf-8")
    return done


def update_readmes(cfg: dict[str, Any], R: dict[str, Any] | None, summ: pd.DataFrame | None = None, paths: tuple[Path, ...] = READMES) -> list[str]:
    """`update_readme` for every README that exists (English and Vietnamese); returns `"<file>: <block>"` for each block written."""
    return [f"{p.name}: {name}" for p in paths if Path(p).exists() for name in update_readme(p, cfg, R, summ)]
